services:
  postgres:
    image: postgres:17-alpine
    container_name: postgresCMI 
    environment:
      POSTGRES_USER: minotaurthegreat11
      POSTGRES_PASSWORD: adabobby2003
      POSTGRES_DB: cmi_webapp
    ports:
      - "5432:5432"  # Change this back to the default
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminCMI
    environment:
      PGADMIN_DEFAULT_EMAIL: minotaurthegreat11@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adabobby2003
    ports:
      - "5050:80"  # Keep pgAdmin on port 5050
    depends_on:
      - postgres
    restart: unless-stopped
